when:
  - event: [push, manual]
    branch: develop

workspace:
  - path: /home/denis/programs/Math/yutovo/deploy/
  
steps:
  - name: build
    image: ubuntu:22.04
    commands:
      - apt update && apt install -y build-essential cmake libmpfr-dev
      - mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug ..
      - make -sj4