when:
  - event: [push, manual]
    branch: develop

workspace:
  base: /denis/programs/Math/yutovo
  path: deploy

steps:
  - name: build
    image: ubuntu:22.04
    commands:
      - apt update && apt install -y build-essential cmake libmpfr-dev
      - export YUTOVO_DEPLOY=/home/denis/programs/Math/yutovo/deploy
      - ls -la $YUTOVO_DEPLOY
      - mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug ..
      - make -sj4